### ISSUE TITLE
Directus nuxt current user info

### ISSUE THREAD

**Issue by amaraad** [Intevel/nuxt-directus#201]
### Version

nuxt-directus: 5.5
nuxt: 3.5.0

### What is actually happening?
[Directus Error]: FetchError: fetch failed (http://localhost:8055/users/me)                                                                                5:54:53 PM
Couldn't fetch user TypeError: Cannot read properties of undefined (reading '_data')

**Comment by Intevel** [comment]
@amaraad Can you provide a reproduction link? I can't reproduce this, and there is no other user facing this issue.

**Comment by yavuz** [comment]
I'm experiencing the same issue. When I navigate between pages, I constantly get this error.

```
 ERROR  [Directus Error]: FetchError: [GET] "http://localhost:8055/users/me": <no response> fetch failed


 ERROR  Couldn't fetch user Cannot read properties of undefined (reading '_data')

  at node_modules/nuxt-directus/dist/runtime/composables/useDirectus.mjs:32:34
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async fetchUser (node_modules/nuxt-directus/dist/runtime/composables/useDirectusAuth.mjs:49:23)
  at async checkIfUserExists (node_modules/nuxt-directus/dist/runtime/plugin.mjs:19:9)
  at async node_modules/nuxt-directus/dist/runtime/plugin.mjs:24:86
  at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
  at async applyPlugin (node_modules/nuxt/dist/app/nuxt.js:146:25)
  at async executePlugin (node_modules/nuxt/dist/app/nuxt.js:183:9)
  at async Module.applyPlugins (node_modules/nuxt/dist/app/nuxt.js:197:5)
  at async createNuxtAppServer (node_modules/nuxt/dist/app/entry.js:23:7)


 WARN  [nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload.
```
 
 I'm running Directus and Nuxt with Docker. Here's my docker-compose.yml file:
``` 
services:
  directus:
    image: directus/directus:11.3.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      ACCESS_TOKEN_TTL: "30d"
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "yvzyldrm@gmail.com"
      ADMIN_PASSWORD: "yavuzyildirim"
      DB_CLIENT: "mysql"
      DB_HOST: "host.docker.internal"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: "1"
      DB_NAME: "directus_db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://nuxt:3000,http://localhost:3000"
      CORS_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
      CORS_EXPOSED_HEADERS: "Content-Range"
      CORS_CREDENTIALS: "true"
      CORS_MAX_AGE: "18000"
    env_file:
      - .env
    networks:
      - app_network

  redis:
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/redis-data
    command: redis-server --appendonly yes
    networks:
      - app_network

  nuxt:
    image: node:22
    container_name: nuxt
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - directus
    networks:
      - app_network

  python-service:
    image: python:3.12-slim
    container_name: python-service
    working_dir: /app
    build:
      context: ./python-service  # Dockerfile'ın bulunduğu klasör
      dockerfile: Dockerfile
    volumes:
      - ./python-service:/app
    command: /bin/sh -c "pip install -r requirements.txt && cron -f"
    depends_on:
      - directus
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
```

Here's my middleware/auth.ts file:

```
export default defineNuxtRouteMiddleware(async (to, _from) => {
    const { fetchUser, setUser } = useDirectusAuth();
    const userState = useDirectusUser();

    try {
        if (!userState.value) {
            const fetchedUser = await fetchUser();
            if (fetchedUser?.value) {
                setUser(fetchedUser.value);
            } else {
                return navigateTo("/signin");
            }
        }
    } catch (error) {
        console.error('Authentication error:', error);
        return navigateTo("/signin");
    }
});
```

Due to the error I'm encountering, it redirects me to the /signin page. @amaraad How did you solve this?
