### ISSUE TITLE
Client/Server side directus url

### ISSUE THREAD

**Issue by ulysse-lacour** [Intevel/nuxt-directus#268]
Hello all, seems the module is missing a real important feature for server/client data fetching within docker dev image.
Following the docs i added a directusUrl value in config and I'm using useAsyncData to fetch.  (had cors issues I managed to fix)

My problem is simple : I can only make fetch work eitehr server (using directus docker image path like directus:PORT) or client side (using localhost:PORT.

From the docs we only have one value for directus url, how to toggle between server/client url or so ?

Thanks!

**Comment by Sandros94** [comment]
With nuxt-directus v5 this isn't possible, although it is something I've considered while rewriting the module for v6.

On the other hand, I imagine you are deploying a docker compose, you shouldn't refer to `localhost`, since each container will point to their own interface.
To solve this in production you need some sort of reverse proxy like caddy or nginx and point to the public ip of your server, then the internal docker network will do the rest (making sure internal requests between nuxt -> directus are handled directly).
While during development I suggest you to use `http://host.docker.internal:8055` (if you are using directus's default `8055` port). To put it simply: this is an internal address that docker uses to connect all the containers to when you add the `port: -X:X` to your compose or run command, making sure that both the host system and other containers are able to find each other.

**Comment by ulysse-lacour** [comment]
Thank you for you help, I haven't uploaded anything to production yet so I was really focused on docker dev setup but I finally found a way, which is to add network mode  to host on both containers (nuxt and directus) which absolutely did the trick! 

This is my current docker compose for dev :

```
version: "3"
services:

  database:
    image: postgis/postgis:13-master
    container_name: ${PROJECT_NAME}__database
    platform: linux/amd64

    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    command: -p ${DB_PORT}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus -p ${DB_PORT}"]
      interval: 5s
      timeout: 1s
      retries: 5

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}

    volumes:
      - ./postgres/data/database:/var/lib/postgresql/data


  cache:
    image: redis:6
    container_name: ${PROJECT_NAME}__cache
    network_mode: host


  directus:
    image: ${PROJECT_NAME}__directus
    container_name: ${PROJECT_NAME}__directus
    network_mode: host

    build:
      context: ./directus
      dockerfile: ./Dockerfile

    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started

    environment:
      SECRET: ${SECRET}
      PUBLIC_URL: ${DIRECTUS_URL}
      PORT: ${DIRECTUS_PORT}
      DB_CLIENT: "pg"
      DB_HOST: "localhost"
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PWD}
      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://localhost:6379"
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PWD}
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_ANCESTORS: array:http://localhost:*,self
      MARKETPLACE_TRUST: all
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'

    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/templates:/directus/templates
      - ./directus/snapshots:/directus/snapshots
      - ./directus/directus-config:/directus/directus-config
      - ./directus/directus-sync.config.cjs:/directus/directus-sync.config.cjs


  nuxt:
    image: ${PROJECT_NAME}__nuxt
    container_name: ${PROJECT_NAME}__nuxt
    network_mode: host

    build:
      context: ./nuxt
      dockerfile: ./Dockerfile.dev

    tmpfs: /tmp

    environment:
      PORT: ${NUXT_PORT}
      DIRECTUS_URL: ${DIRECTUS_URL}

    depends_on:
      - directus

    volumes:
      - ./nuxt:/nuxt-app
      - /nuxt-app/node_modules
```
