### ISSUE TITLE
What is the strategy for extending a users session?

### ISSUE THREAD

**Issue by Maximus-5** [Intevel/nuxt-directus#284]
I'm new to Nuxt and Directus

My main question is does Nuxt-Directus have a strategy or recommendation for extending the session?

I've tried the directus sdk and found it left managing the directus session to the developer (I think....)

This is the second time I've tried nuxt-directus in my code, login and logout works but automatic logout happens after about 15 minutes.

Can we extend the session inside middleware?
Right now I'm using something like this:
```js
//MyPage.vue
<script setup>
const { refreshTokens } = useDirectusToken();
refreshTokens()
```
this is being done in the Vue file, which I feel is not ideal, but for some reason this code did not function properly in middleware.

Thanks for reading.

**Comment by Intevel** [comment]
This maybe is a bug related to an other issue. I will check this

**Comment by mahsamirzapour** [comment]
Same, even I have been reported that bug, when I refresh the browser the session removed!

**Comment by Nisthar** [comment]
You don't need to manually refresh the tokens Right? it happens automatically using the module.

**Comment by mahsamirzapour** [comment]
@Nisthar  The session does not kept on cookies and logout happens after refresh the browser, I installed version 5.6.1 and it's works fine, the issue caused by latest version

**Comment by sandros94** [comment]
> You don't need to manually refresh the tokens Right? it happens automatically using the module.

indeed:
https://github.com/Intevel/nuxt-directus/blob/706fa0482b14944d49874e967d3d1ae27daff1cb/src/runtime/plugin.ts#L11

although since nuxt 3.12 (iirc) the current approach can be inconsistent for ssr (it would require [`useRequestFetch`](https://nuxt.com/docs/api/composables/use-request-fetch) under the hood). This creates a number of edge cases that all need different approaches (it was already part of my rewrite, that I started a year ago 😔)

@Maximus-5 could you tell me if you self host directus via Docker? There is also another edge-case there that makes sessions last exactly 15 minutes. But I need to dig into my notes, since it has been some time since last time I encountered this. If so, could you also share the docker-compose file?

**Comment by Maximus-5** [comment]
@sandros94 
```yaml
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    expose:
      - "8055"
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "example"
      ADMIN_EMAIL: "example@example.com"
      ADMIN_PASSWORD: "example"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/database.sqlite"
      WEBSOCKETS_ENABLED: "true"
      PUBLIC_URL: http://mysite.com
      TELEMETRY: false
```

Thanks for your reply.
The compose is something like this, we are also using caddy.

```js
// refresh http request using a cookie
const result = await client.request(refresh('cookie'));

// refresh http request using json
const result = await client.request(refresh('json', refresh_token));
```

I was just wondering, what is the difference in directus for using a cookie or json for auth?
I don't think the benefits of each approach are covered in the documentation.
